/**
 * Design tokens extracted from Google Stitch HTML exports in:
 * `reference/stitch-html/*_web/code.html`
 */
export const designTokens = {
  "on-secondary-fixed-variant": "#3a485c",
  "tertiary-fixed": "#6ffbbe",
  "secondary-fixed": "#d5e3fd",
  "on-tertiary-fixed-variant": "#005236",
  "on-tertiary-fixed": "#002113",
  "on-surface-variant": "#45464d",
  "on-primary-container": "#7c839b",
  error: "#ba1a1a",
  "outline-variant": "#c6c6cd",
  "error-container": "#ffdad6",
  "inverse-primary": "#bec6e0",
  "inverse-on-surface": "#eaf1ff",
  "surface-container": "#e5eeff",
  "primary-fixed": "#dae2fd",
  "on-primary-fixed-variant": "#3f465c",
  secondary: "#515f74",
  tertiary: "#000000",
  "tertiary-fixed-dim": "#4edea3",
  "surface-variant": "#d3e4fe",
  "on-tertiary-container": "#009668",
  "surface-dim": "#cbdbf5",
  "on-error-container": "#93000a",
  "surface-container-lowest": "#ffffff",
  "on-background": "#0b1c30",
  "on-primary-fixed": "#131b2e",
  "surface-container-high": "#dce9ff",
  "inverse-surface": "#213145",
  "surface-bright": "#f8f9ff",
  "secondary-fixed-dim": "#b9c7e0",
  "secondary-fixed-variant": "#5c6b82",
  surface: "#f8f9ff",
  "secondary-container": "#d5e3fd",
  primary: "#000000",
  "on-surface": "#0b1c30",
  "tertiary-container": "#002113",
  "surface-container-highest": "#d3e4fe",
  outline: "#76777d",
  "on-secondary-fixed": "#0d1c2f",
  "on-secondary": "#ffffff",
  "primary-fixed-dim": "#bec6e0",
  "primary-container": "#131b2e",
  "on-secondary-container": "#57657b",
  background: "#f8f9ff",
  "on-tertiary": "#ffffff",
  "surface-tint": "#565e74",
  "on-error": "#ffffff",
  "surface-container-low": "#eff4ff",
  "on-primary": "#ffffff",
};
